-- users table 
CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(250) UNIQUE NOT NULL,
  name VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
  rol VARCHAR(250),
  phone VARCHAR(250),
  address VARCHAR(250)
);